version: 5.1.0
variant: default
logo: ''
head:
    favicon: https://avatars.githubusercontent.com/u/84729199?s=400&u=7d8faf6aeb2c7790f9770f718609c65eb5278114&v=4
    manifest:
        name: Iphigenie Bera
        short_name: Bera
        start_url: 
        theme_color: '#f7f7f7'
        background_color: '#f7f7f7'
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        About: /about
        Archives: /archives
        Categories: /categories
        Resume: /IphigenieBeraResume.pdf
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/IphixLi
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-dark
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
share:
    type: sharethis
    install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-62f30acb0a28e668
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Iphigenie Bera
        author_title: Computer Science
        location: Evanston,Illinois
        avatar: https://avatars.githubusercontent.com/u/84729199?s=400&u=7d8faf6aeb2c7790f9770f718609c65eb5278114&v=4
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/IphixLi
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/IphixLi
            linkedIn:
                icon: fab fa-linkedin
                url: https://www.linkedin.com/in/berami/
            Instagram:
                icon: fab fa-instagram
                url: https://www.instagram.com/bera_iphix/
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Kaggle: https://www.kaggle.com/iphigeniebera
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: right
        type: archives
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
